sberbank:
  potrošniški: https://pcbu27f2x0.execute-api.eu-west-1.amazonaws.com/dev/sberbank/potrosniski
  stanovanjski: https://pcbu27f2x0.execute-api.eu-west-1.amazonaws.com/dev/sberbank/stanovanjski
  avtomobilski: https://pcbu27f2x0.execute-api.eu-west-1.amazonaws.com/dev/sberbank/avtomobilski
  gotovinski: https://pcbu27f2x0.execute-api.eu-west-1.amazonaws.com/dev/sberbank/gotovinski
  hitri: https://pcbu27f2x0.execute-api.eu-west-1.amazonaws.com/dev/sberbank/hitri
     
skb:
  stanovanjski: https://pcbu27f2x0.execute-api.eu-west-1.amazonaws.com/dev/skb/stanovanjski
  potrošniški: https://pcbu27f2x0.execute-api.eu-west-1.amazonaws.com/dev/skb/potrosniski

sparkasse:
  stanovanjski: https://pcbu27f2x0.execute-api.eu-west-1.amazonaws.com/dev/sparkasse/stanovanjski
  potrošniški: https://pcbu27f2x0.execute-api.eu-west-1.amazonaws.com/dev/sparkasse/potrosniski
  hitri: https://pcbu27f2x0.execute-api.eu-west-1.amazonaws.com/dev/sparkasse/hitri

unicredit:
  potrošniški: https://pcbu27f2x0.execute-api.eu-west-1.amazonaws.com/dev/unicredit/potrosniski
  stanovanjski: https://pcbu27f2x0.execute-api.eu-west-1.amazonaws.com/dev/unicredit/stanovanjski
